name: send_debug_info
description: A Flutter example using Maps SDK for Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  share_plus: ^11.0.0

  magiclane_maps_flutter: ^3.1.2

  permission_handler: ^12.0.1
  debug_console: ^0.0.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
