name: send_debug_info
description: A Flutter example using Maps SDK for Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.0
  share_plus: ^7.0.0

  gem_kit:
    path: plugins/gem_kit

  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1
  debug_console: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  patrol: ^3.11.1

flutter:
  uses-material-design: true
patrol:
  app_name: My App

  android:
    package_name: com.magiclane.gem_kit.examples.send_debug_info
  ios:
    bundle_id: com.example.MyApp
