name: driver_behaviour
description: A Flutter example using Maps SDK for Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  magiclane_maps_flutter: ^3.0.0

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  patrol: ^3.17.0

flutter:
  uses-material-design: true
patrol:
  app_name: My App

  android:
    package_name: com.magiclane.magiclane_maps_flutter.examples.driver_behaviour
  ios:
    bundle_id: com.example.MyApp
