name: public_transit_stop_schedule
description: A Flutter example using Maps SDK for Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  magiclane_maps_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  intl: ^0.20.2

flutter:
  uses-material-design: true