version = 1

SPDX-PackageName = "maps-sdk-examples-for-flutter"
SPDX-PackageSupplier = "magiclane-developer@users.noreply.github.com"
SPDX-PackageDownloadLocation = "https://github.com/magiclane-international/maps-sdk-examples-for-flutter"
SPDX-PackageComment = "A collection of sample projects to support application development with the Magic Lane Maps SDK for Flutter."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "1995-2025 Magic Lane International B.V. <info@magiclane.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "**/gradle/**",
    "**/gradlew",
    "**/gradlew.bat",
    "**/gradle.properties"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"
