name: map_update
description: A Flutter example using Maps SDK for Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  gem_kit:
    path: plugins/gem_kit

  cupertino_icons: ^1.0.8
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
